### ISSUE TITLE
Relationship field not validating/required

### ISSUE THREAD

**Issue by AlexAndBear** [marshmallow-code/flask-marshmallow#149] opened 2019-09-12 14:42 UTC
Hi there,
I am wondering why there is no need to add a relationship field while it is required in the model.

Example:

models/notification.py
```
class Notification(db.Model, Timestamp):
    id = db.Column(db.Integer, primary_key=True)
    rule_id = db.Column(db.Integer, db.ForeignKey('rule.id'), nullable=False)
    rule = db.relationship("Rule", backref="notifications")
```

models/rule.py
```
class Rule(db.Model, Timestamp):
    message = db.Column(db.String(500), nullable=False)
```

schema/base_schema.py
```
class BaseSchema(ma.ModelSchema):
    id = fields.Integer(dump_only=True)
    created = fields.DateTime(dump_only=True)
    updated = fields.DateTime(dump_only=True)

    class Meta:
        sqla_session = db.session
```

schema/notification.py
```
class NotificationSchema(BaseSchema):

    class Meta(BaseSchema.Meta):
        model = Notification
```

Post Endpoint
```
@blueprint_api_v1_notifications.route('', methods=['POST'])
def add_notification():
    notification_data = request.get_json(force=True)

    schema = NotificationSchema()
    notification = schema.load(notification_data)

    db.session.add(notification)
    db.session.commit()

    return make_response(
        jsonify(schema.dump(notification)),
        201
    )
```

If ll do now a post without rule relation in request body, ill end up with an SQLALCHEMY null constraint exception
```
{
  "error": "(psycopg2.errors.NotNullViolation) null value in column \"rule_id\" violates not-null constraint\nDETAIL:  Failing row contains (2019-09-12 14:33:35.016647, 2019-09-12 14:33:35.016659, 27, null).\n\n[SQL: INSERT INTO notification (created, updated, rule_id) VALUES (%(created)s, %(updated)s, %(rule_id)s) RETURNING notification.id]\n[parameters: {'created': datetime.datetime(2019, 9, 12, 14, 33, 35, 16647), 'updated': datetime.datetime(2019, 9, 12, 14, 33, 35, 16659), 'rule_id': None}]\n(Background on this error at: http://sqlalche.me/e/gkpj)"
}
```

In my opinion it should be checked if field rule is inside the post json and raise an exception if not.

**Comment by kakul232** [comment] 2020-01-24 12:02
you need to parse the error using 
`app.register_error_handler(DatabaseError, your_function)`

**Comment by sloria** [comment] 2020-04-26 18:08
I think the issue is that `rule_id` isn't getting autogenerated by `ModelSchema`. You can try setting `include_fk = True`. The better option is to use `SQLAlchemySchema`.

Closing for now, but feel free to comment if you're still experiencing the issue

**Closed as completed by sloria** 2020-04-26 18:08 UTC
