### ISSUE TITLE
AttributeError: 'Marshmallow' object has no attribute 'HyperlinkModelSchema'

### ISSUE THREAD

**Issue by tnemalili** [marshmallow-code/flask-marshmallow#47] opened 2016-06-22 19:49 UTC
ma = Marshmallow(app)
class AuthorSchema(ma.HyperlinkModelSchema):
    ....
    ......
AttributeError: 'Marshmallow' object has no attribute 'HyperlinkModelSchema'

**Comment by dequis** [comment] 2016-08-01 22:04
Duplicate of #30, already fixed with #39

tl;dr HyperlinkModelSchema doesn't exist and never did, use HyperlinkRelated.

**Closed as completed** 2023-04-13 14:49 UTC
